cp Plots_PhotonSusyAnalysis/PlotsFOComparisonBeforeFitData/c_DivideXPreselCut_metVsPhotonPt_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_3jet_Data.root 
cp Plots_PhotonSusyAnalysis/PlotsFOComparisonBeforeFitDijetData/c_DivideXPreselCut_metVsPhotonPt_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_2jet_Data.root

cp Plots_PhotonSusyAnalysis/PlotsFOComparisonBeforeFitDijetQCDandPhotonJet/c_DivideXPreselCut_metVsPhotonPt_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_2jet_MC.root 
cp Plots_PhotonSusyAnalysis/PlotsFOComparisonBeforeFitQCDandPhotonJet/c_DivideXPreselCut_metVsPhotonPt_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_3jet_MC.root

cp Plots_PhotonSusyAnalysis/PlotsFOComparisonData/c_DivideXPreselCut_metVsnoJet_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_noJet_3jet_Data.root
cp Plots_PhotonSusyAnalysis/PlotsFOComparisonDijetData/c_DivideXPreselCut_metVsnoJet_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_noJet_2jet_Data.root
cp Plots_PhotonSusyAnalysis/PlotsFOComparisonDijetMCQCDandPhotonJet/c_DivideXPreselCut_metVsnoJet_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_noJet_2jet_MC.root
cp Plots_PhotonSusyAnalysis/PlotsFOComparisonMCQCDandPhotonJet/c_DivideXPreselCut_metVsnoJet_Bin_From_0_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_noJet_3jet_MC.root

###########USE ==2 jet Histogram for 2-jet bins !!!!!!!!!!!!!!
cp Plots_PhotonSusyAnalysis/PlotsFOComparisonBeforeFitDijetQCDandPhotonJet/c_DivideXPreselCut_noJetsVsPhotonPtLowMet_Bin_From_2_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_2jet_MC.root 
cp Plots_PhotonSusyAnalysis/PlotsFOComparisonBeforeFitDijetData/c_DivideXPreselCut_noJetsVsPhotonPtLowMet_Bin_From_2_CompTightLoose_RAT.root PhotonSusyAnalysis/SelectionAnalyzer/data/QCDEst_2jet_Data.root 
